//! CI entry point for the personal-data classification gate.
//!
//! `--inventory` prints the parsed table/column set and is how the baseline is
//! produced. The baseline is therefore generated by the same parser that
//! enforces it: a second, hand-maintained inventory would be free to disagree
//! with the gate about what a column is.

use std::path::Path;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let workspace_dir = match std::env::current_dir() {
        Ok(dir) => dir,
        Err(e) => {
            eprintln!("ERROR: cannot determine cwd: {e}");
            std::process::exit(1);
        }
    };

    match args.first().map(String::as_str) {
        Some("--inventory") => inventory(&workspace_dir),
        Some("--citations") => citations(),
        Some(other) => {
            eprintln!("ERROR: unknown argument '{other}' (expected --inventory or --citations)");
            std::process::exit(2);
        }
        None => run_gate(&workspace_dir),
    }
}

fn run_gate(workspace_dir: &Path) {
    eprintln!(
        "console-gate-personal-data-classification: checking workspace at {}",
        workspace_dir.display()
    );

    let result = console_gate_personal_data_classification::check_workspace(workspace_dir)
        .unwrap_or_else(|e| {
            eprintln!("ERROR: {e}");
            std::process::exit(1);
        });

    eprintln!(
        "console-gate-personal-data-classification: {} table(s), {} column(s); \
         {} column(s) classified; {} table(s) still baselined",
        result.total_tables,
        result.total_columns,
        result.classified_columns,
        result.baselined_tables
    );

    if result.passed() {
        eprintln!("console-gate-personal-data-classification: PASSED");
        std::process::exit(0);
    }

    eprintln!(
        "console-gate-personal-data-classification: FAILED - {} violation(s):",
        result.violations.len()
    );
    for violation in &result.violations {
        eprintln!("  {violation}");
    }
    std::process::exit(1);
}

fn inventory(workspace_dir: &Path) {
    let files = console_gate_personal_data_classification::collect_migration_files(workspace_dir)
        .unwrap_or_else(|e| {
            eprintln!("ERROR: {e}");
            std::process::exit(1);
        });
    let schema = console_gate_personal_data_classification::parse_schema(&files);
    for (table, columns) in &schema.tables {
        for column in columns {
            println!("{table}\t{column}");
        }
    }
    eprintln!(
        "{} table(s), {} column(s)",
        schema.tables.len(),
        schema.column_count()
    );
}

fn citations() {
    for entry in console_gate_personal_data_classification::VOCABULARY {
        println!(
            "{}\t{}\t{}\t시행 {}\t{}",
            entry.token,
            entry.instrument,
            entry.article,
            entry.effective,
            if entry.subtokens.is_empty() {
                "-".to_owned()
            } else {
                entry.subtokens.join("|")
            }
        );
    }
}
